"""baseline schema

Revision ID: e5f8fef9a71b
Revises:
Create Date: 2026-07-30 19:07:22.827397
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e5f8fef9a71b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_runs",
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_params", sa.JSON(), nullable=False),
        sa.Column("symbols", sa.JSON(), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum(
                "1m",
                "3m",
                "5m",
                "15m",
                "30m",
                "1h",
                "2h",
                "4h",
                "6h",
                "8h",
                "12h",
                "1d",
                "3d",
                "1w",
                name="timeframe_enum",
            ),
            nullable=False,
        ),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "completed", "failed", "cancelled", name="run_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("starting_equity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("final_equity", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("total_return_pct", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("sharpe_ratio", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("sortino_ratio", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("max_drawdown_pct", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("win_rate", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("profit_factor", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("report_path", sa.String(length=512), nullable=True),
        sa.Column("duration_seconds", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_runs")),
    )
    op.create_index(
        op.f("ix_backtest_runs_created_at"), "backtest_runs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_backtest_runs_strategy_created",
        "backtest_runs",
        ["strategy_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backtest_runs_strategy_id"), "backtest_runs", ["strategy_id"], unique=False
    )
    op.create_table(
        "candles",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum(
                "1m",
                "3m",
                "5m",
                "15m",
                "30m",
                "1h",
                "2h",
                "4h",
                "6h",
                "8h",
                "12h",
                "1d",
                "3d",
                "1w",
                name="timeframe_enum",
            ),
            nullable=False,
        ),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("high", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("low", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("close", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("volume", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("quote_volume", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("trades", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            '"close" BETWEEN low AND high', name=op.f("ck_candles_close_within_range")
        ),
        sa.CheckConstraint(
            '"open" BETWEEN low AND high', name=op.f("ck_candles_open_within_range")
        ),
        sa.CheckConstraint("high >= low", name=op.f("ck_candles_high_ge_low")),
        sa.CheckConstraint("low >= 0", name=op.f("ck_candles_low_non_negative")),
        sa.CheckConstraint("volume >= 0", name=op.f("ck_candles_volume_non_negative")),
        sa.PrimaryKeyConstraint("symbol", "timeframe", "open_time", name=op.f("pk_candles")),
    )
    op.create_index(
        "ix_candles_symbol_tf_time", "candles", ["symbol", "timeframe", "open_time"], unique=False
    )
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("market_type", sa.String(length=16), nullable=False),
        sa.Column("base_asset", sa.String(length=16), nullable=False),
        sa.Column("quote_asset", sa.String(length=16), nullable=False),
        sa.Column("price_tick", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("quantity_step", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("min_quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("max_quantity", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("min_notional", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("max_notional", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("maker_fee", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("taker_fee", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("max_leverage", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("contract_size", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint(
            "exchange",
            "symbol",
            "market_type",
            name=op.f("uq_instruments_exchange_symbol_market_type"),
        ),
    )
    op.create_index(op.f("ix_instruments_created_at"), "instruments", ["created_at"], unique=False)
    op.create_index(op.f("ix_instruments_symbol"), "instruments", ["symbol"], unique=False)
    op.create_table(
        "journal_entries",
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=True),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("strengths", sa.JSON(), nullable=False),
        sa.Column("weaknesses", sa.JSON(), nullable=False),
        sa.Column("recommendations", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
    )
    op.create_index(
        op.f("ix_journal_entries_created_at"), "journal_entries", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_period_end"), "journal_entries", ["period_end"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_strategy_id"), "journal_entries", ["strategy_id"], unique=False
    )
    op.create_table(
        "kill_switch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("engaged", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("engaged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("engaged_by", sa.String(length=64), nullable=True),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleared_by", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kill_switch")),
    )
    op.create_index(op.f("ix_kill_switch_created_at"), "kill_switch", ["created_at"], unique=False)
    op.create_table(
        "optimization_runs",
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("objective", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "completed", "failed", "cancelled", name="run_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("search_space", sa.JSON(), nullable=False),
        sa.Column("trials_requested", sa.Integer(), nullable=False),
        sa.Column("trials_completed", sa.Integer(), nullable=False),
        sa.Column("best_params", sa.JSON(), nullable=False),
        sa.Column("best_value", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("in_sample_value", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("out_of_sample_value", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optimization_runs")),
    )
    op.create_index(
        op.f("ix_optimization_runs_created_at"), "optimization_runs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_optimization_runs_strategy_id"), "optimization_runs", ["strategy_id"], unique=False
    )
    op.create_table(
        "regime_observations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum(
                "1m",
                "3m",
                "5m",
                "15m",
                "30m",
                "1h",
                "2h",
                "4h",
                "6h",
                "8h",
                "12h",
                "1d",
                "3d",
                "1w",
                name="timeframe_enum",
            ),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "regime",
            sa.Enum(
                "bull_trend",
                "bear_trend",
                "range",
                "high_volatility",
                "unknown",
                name="market_regime_enum",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regime_observations")),
        sa.UniqueConstraint(
            "symbol",
            "timeframe",
            "timestamp",
            name="uq_regime_observations_symbol_timeframe_timestamp",
        ),
    )
    op.create_index(
        op.f("ix_regime_observations_symbol"), "regime_observations", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_regime_observations_timestamp"), "regime_observations", ["timestamp"], unique=False
    )
    op.create_table(
        "sentiment_observations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("magnitude", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sentiment_observations")),
    )
    op.create_index(
        op.f("ix_sentiment_observations_observed_at"),
        "sentiment_observations",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sentiment_observations_symbol"), "sentiment_observations", ["symbol"], unique=False
    )
    op.create_index(
        "ix_sentiment_symbol_time",
        "sentiment_observations",
        ["symbol", "observed_at"],
        unique=False,
    )
    op.create_table(
        "trading_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "completed", "failed", "cancelled", name="run_status_enum"
            ),
            nullable=False,
        ),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("strategy_params", sa.JSON(), nullable=False),
        sa.Column("symbols", sa.JSON(), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum(
                "1m",
                "3m",
                "5m",
                "15m",
                "30m",
                "1h",
                "2h",
                "4h",
                "6h",
                "8h",
                "12h",
                "1d",
                "3d",
                "1w",
                name="timeframe_enum",
            ),
            nullable=False,
        ),
        sa.Column("base_currency", sa.String(length=16), nullable=False),
        sa.Column("starting_equity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("final_equity", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_config", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_sessions")),
    )
    op.create_index(
        op.f("ix_trading_sessions_created_at"), "trading_sessions", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_trading_sessions_mode"), "trading_sessions", ["mode"], unique=False)
    op.create_index(
        op.f("ix_trading_sessions_strategy_id"), "trading_sessions", ["strategy_id"], unique=False
    )
    op.create_table(
        "closed_trades",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "side", sa.Enum("long", "short", "flat", name="position_side_enum"), nullable=False
        ),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("entry_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exit_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gross_pnl", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("fees", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("net_pnl", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("return_pct", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("holding_period_seconds", sa.BigInteger(), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=True),
        sa.Column(
            "regime",
            sa.Enum(
                "bull_trend",
                "bear_trend",
                "range",
                "high_volatility",
                "unknown",
                name="market_regime_enum",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["trading_sessions.id"],
            name=op.f("fk_closed_trades_session_id_trading_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_closed_trades")),
    )
    op.create_index(
        op.f("ix_closed_trades_exit_time"), "closed_trades", ["exit_time"], unique=False
    )
    op.create_index(
        "ix_closed_trades_session_exit", "closed_trades", ["session_id", "exit_time"], unique=False
    )
    op.create_index(
        "ix_closed_trades_strategy_exit",
        "closed_trades",
        ["strategy_id", "exit_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_closed_trades_strategy_id"), "closed_trades", ["strategy_id"], unique=False
    )
    op.create_index(op.f("ix_closed_trades_symbol"), "closed_trades", ["symbol"], unique=False)
    op.create_table(
        "equity_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("equity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("cash", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("position_count", sa.Integer(), nullable=False),
        sa.Column("gross_exposure", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("drawdown_pct", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["trading_sessions.id"],
            name=op.f("fk_equity_snapshots_session_id_trading_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equity_snapshots")),
        sa.UniqueConstraint(
            "session_id", "timestamp", name="uq_equity_snapshots_session_id_timestamp"
        ),
    )
    op.create_index(
        "ix_equity_snapshots_session_time",
        "equity_snapshots",
        ["session_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("venue_order_id", sa.String(length=64), nullable=True),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.Enum("buy", "sell", name="order_side_enum"), nullable=False),
        sa.Column(
            "order_type",
            sa.Enum(
                "market",
                "limit",
                "stop_market",
                "stop_limit",
                "take_profit_market",
                "take_profit_limit",
                name="order_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending_new",
                "new",
                "partially_filled",
                "filled",
                "pending_cancel",
                "cancelled",
                "rejected",
                "expired",
                name="order_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "time_in_force",
            sa.Enum("gtc", "ioc", "fok", "gtd", name="time_in_force_enum"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("trigger_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("filled_quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("average_fill_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("fees_paid", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("stop_loss_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("take_profit_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("reduce_only", sa.Boolean(), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=True),
        sa.Column("signal_id", sa.String(length=64), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "filled_quantity <= quantity", name=op.f("ck_orders_filled_within_quantity")
        ),
        sa.CheckConstraint("filled_quantity >= 0", name=op.f("ck_orders_filled_non_negative")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_orders_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["trading_sessions.id"],
            name=op.f("fk_orders_session_id_trading_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("client_order_id", name="uq_orders_client_order_id"),
    )
    op.create_index(op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False)
    op.create_index("ix_orders_session_status", "orders", ["session_id", "status"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_strategy_id"), "orders", ["strategy_id"], unique=False)
    op.create_index(op.f("ix_orders_symbol"), "orders", ["symbol"], unique=False)
    op.create_index("ix_orders_symbol_created", "orders", ["symbol", "created_at"], unique=False)
    op.create_index(op.f("ix_orders_venue_order_id"), "orders", ["venue_order_id"], unique=False)
    op.create_table(
        "positions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "side", sa.Enum("long", "short", "flat", name="position_side_enum"), nullable=False
        ),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("average_entry_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("fees_paid", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("stop_loss_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("take_profit_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("strategy_id", sa.String(length=64), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lots", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["trading_sessions.id"],
            name=op.f("fk_positions_session_id_trading_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_index(op.f("ix_positions_created_at"), "positions", ["created_at"], unique=False)
    op.create_index("ix_positions_open", "positions", ["session_id", "closed_at"], unique=False)
    op.create_index(
        "ix_positions_session_symbol", "positions", ["session_id", "symbol"], unique=False
    )
    op.create_index(op.f("ix_positions_strategy_id"), "positions", ["strategy_id"], unique=False)
    op.create_index(op.f("ix_positions_symbol"), "positions", ["symbol"], unique=False)
    op.create_table(
        "risk_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("rule", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("observed_value", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("limit_value", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("blocked_order", sa.Boolean(), nullable=False),
        sa.Column("halted_trading", sa.Boolean(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["trading_sessions.id"],
            name=op.f("fk_risk_events_session_id_trading_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_events")),
    )
    op.create_index(op.f("ix_risk_events_created_at"), "risk_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_risk_events_rule"), "risk_events", ["rule"], unique=False)
    op.create_index(
        "ix_risk_events_session_created", "risk_events", ["session_id", "created_at"], unique=False
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("conviction", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reference_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("stop_loss_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("take_profit_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column(
            "regime",
            sa.Enum(
                "bull_trend",
                "bear_trend",
                "range",
                "high_volatility",
                "unknown",
                name="market_regime_enum",
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("acted_on", sa.Boolean(), nullable=False),
        sa.Column("rejection_rule", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["trading_sessions.id"],
            name=op.f("fk_signals_session_id_trading_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index(op.f("ix_signals_strategy_id"), "signals", ["strategy_id"], unique=False)
    op.create_index(
        "ix_signals_strategy_time", "signals", ["strategy_id", "timestamp"], unique=False
    )
    op.create_index(op.f("ix_signals_symbol"), "signals", ["symbol"], unique=False)
    op.create_index(op.f("ix_signals_timestamp"), "signals", ["timestamp"], unique=False)
    op.create_table(
        "fills",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("venue_fill_id", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.Enum("buy", "sell", name="order_side_enum"), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("fee", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("fee_currency", sa.String(length=16), nullable=False),
        sa.Column("role", sa.Enum("maker", "taker", name="liquidity_role_enum"), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("fee >= 0", name=op.f("ck_fills_fee_non_negative")),
        sa.CheckConstraint("price > 0", name=op.f("ck_fills_price_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_fills_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_fills_order_id_orders"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
        sa.UniqueConstraint("venue_fill_id", "order_id", name="uq_fills_venue_fill_id_order_id"),
    )
    op.create_index("ix_fills_order_time", "fills", ["order_id", "timestamp"], unique=False)
    op.create_index(op.f("ix_fills_symbol"), "fills", ["symbol"], unique=False)
    op.create_index(op.f("ix_fills_timestamp"), "fills", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fills_timestamp"), table_name="fills")
    op.drop_index(op.f("ix_fills_symbol"), table_name="fills")
    op.drop_index("ix_fills_order_time", table_name="fills")
    op.drop_table("fills")
    op.drop_index(op.f("ix_signals_timestamp"), table_name="signals")
    op.drop_index(op.f("ix_signals_symbol"), table_name="signals")
    op.drop_index("ix_signals_strategy_time", table_name="signals")
    op.drop_index(op.f("ix_signals_strategy_id"), table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_risk_events_session_created", table_name="risk_events")
    op.drop_index(op.f("ix_risk_events_rule"), table_name="risk_events")
    op.drop_index(op.f("ix_risk_events_created_at"), table_name="risk_events")
    op.drop_table("risk_events")
    op.drop_index(op.f("ix_positions_symbol"), table_name="positions")
    op.drop_index(op.f("ix_positions_strategy_id"), table_name="positions")
    op.drop_index("ix_positions_session_symbol", table_name="positions")
    op.drop_index("ix_positions_open", table_name="positions")
    op.drop_index(op.f("ix_positions_created_at"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_orders_venue_order_id"), table_name="orders")
    op.drop_index("ix_orders_symbol_created", table_name="orders")
    op.drop_index(op.f("ix_orders_symbol"), table_name="orders")
    op.drop_index(op.f("ix_orders_strategy_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index("ix_orders_session_status", table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_equity_snapshots_session_time", table_name="equity_snapshots")
    op.drop_table("equity_snapshots")
    op.drop_index(op.f("ix_closed_trades_symbol"), table_name="closed_trades")
    op.drop_index(op.f("ix_closed_trades_strategy_id"), table_name="closed_trades")
    op.drop_index("ix_closed_trades_strategy_exit", table_name="closed_trades")
    op.drop_index("ix_closed_trades_session_exit", table_name="closed_trades")
    op.drop_index(op.f("ix_closed_trades_exit_time"), table_name="closed_trades")
    op.drop_table("closed_trades")
    op.drop_index(op.f("ix_trading_sessions_strategy_id"), table_name="trading_sessions")
    op.drop_index(op.f("ix_trading_sessions_mode"), table_name="trading_sessions")
    op.drop_index(op.f("ix_trading_sessions_created_at"), table_name="trading_sessions")
    op.drop_table("trading_sessions")
    op.drop_index("ix_sentiment_symbol_time", table_name="sentiment_observations")
    op.drop_index(op.f("ix_sentiment_observations_symbol"), table_name="sentiment_observations")
    op.drop_index(
        op.f("ix_sentiment_observations_observed_at"), table_name="sentiment_observations"
    )
    op.drop_table("sentiment_observations")
    op.drop_index(op.f("ix_regime_observations_timestamp"), table_name="regime_observations")
    op.drop_index(op.f("ix_regime_observations_symbol"), table_name="regime_observations")
    op.drop_table("regime_observations")
    op.drop_index(op.f("ix_optimization_runs_strategy_id"), table_name="optimization_runs")
    op.drop_index(op.f("ix_optimization_runs_created_at"), table_name="optimization_runs")
    op.drop_table("optimization_runs")
    op.drop_index(op.f("ix_kill_switch_created_at"), table_name="kill_switch")
    op.drop_table("kill_switch")
    op.drop_index(op.f("ix_journal_entries_strategy_id"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_period_end"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_created_at"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_instruments_symbol"), table_name="instruments")
    op.drop_index(op.f("ix_instruments_created_at"), table_name="instruments")
    op.drop_table("instruments")
    op.drop_index("ix_candles_symbol_tf_time", table_name="candles")
    op.drop_table("candles")
    op.drop_index(op.f("ix_backtest_runs_strategy_id"), table_name="backtest_runs")
    op.drop_index("ix_backtest_runs_strategy_created", table_name="backtest_runs")
    op.drop_index(op.f("ix_backtest_runs_created_at"), table_name="backtest_runs")
    op.drop_table("backtest_runs")
    # ### end Alembic commands ###
