"""The structured decision a model must return, and the validation it must survive.

Everything a language model produces is untrusted input. It is text that resembles JSON,
generated by a process with no obligation to be correct, and it is about to be turned into
an order. So parsing here is deliberately strict and deliberately unhelpful: no coercion,
no "did you mean", no salvaging a nearly-valid payload. A malformed decision becomes a
HOLD, because the cost of misreading one is an unintended position and the cost of
rejecting one is waiting five minutes for the next cycle.

Two rules that are not obvious and matter more than the schema:

**A decision the model did not make is a HOLD.** Missing fields, wrong types, an unknown
symbol, a confidence outside [0,1] — all of these fail closed, and the reason is recorded
so the failure is visible rather than silent.

**Prose is not a decision.** Models routinely wrap JSON in explanation or fences. One
fenced block is extracted, because that is a formatting habit rather than a semantic
error. Anything more ambiguous than that is rejected: guessing which of two JSON objects
in a reply is the real answer is exactly the sort of cleverness that produces a trade
nobody intended.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from enum import StrEnum
from typing import Any

from quantflow.core.precision import ZERO
from quantflow.domain.instruments import Symbol

#: A single ```json ... ``` fence, which is a formatting habit rather than an error.
_FENCE = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", re.DOTALL)


class Action(StrEnum):
    """What the model wants to do."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass(frozen=True, slots=True)
class AIDecision:
    """A validated decision. Constructing one means it passed every check."""

    action: Action
    symbol: Symbol
    confidence: Decimal
    reason: str
    #: The raw text the model returned, kept for the audit trail.
    raw: str = ""

    @property
    def is_actionable(self) -> bool:
        """Whether this decision would place an order."""
        return self.action is not Action.HOLD

    def meets(self, threshold: Decimal) -> bool:
        """Whether confidence clears the configured floor."""
        return self.confidence >= threshold

    def to_dict(self) -> dict[str, Any]:
        """Serialise for the journal and the API."""
        return {
            "action": self.action.value,
            "symbol": str(self.symbol),
            "confidence": str(self.confidence),
            "reason": self.reason,
        }


@dataclass(frozen=True, slots=True)
class DecisionError:
    """A decision that could not be trusted, and why.

    Carried rather than raised: a bad response from a model is an ordinary event on a
    loop that runs every few minutes, not an exceptional one, and the loop must keep
    running.
    """

    reason: str
    raw: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialise for the journal."""
        return {"error": self.reason, "raw": self.raw[:2000]}


def parse_decision(  # noqa: PLR0911 - one guarded return per validation rule
    text: str, *, allowed: tuple[Symbol, ...]
) -> AIDecision | DecisionError:
    """Parse and validate a model response.

    Args:
        text: Whatever the model returned.
        allowed: Symbols the service is permitted to trade. A decision naming anything
            else is rejected — a model inventing a ticker must never reach an exchange,
            and "the model asked for it" is not authorisation.

    Returns:
        A validated decision, or a `DecisionError` explaining the refusal.

    """
    if not text or not text.strip():
        return DecisionError("empty response", text or "")

    payload = _extract_json(text)
    if payload is None:
        return DecisionError("no JSON object found in response", text)

    try:
        parsed = json.loads(payload)
    except json.JSONDecodeError as exc:
        return DecisionError(f"malformed JSON: {exc}", text)

    if not isinstance(parsed, dict):
        return DecisionError(f"expected a JSON object, got {type(parsed).__name__}", text)

    action = _parse_action(parsed.get("action"))
    if action is None:
        return DecisionError(f"invalid action {parsed.get('action')!r}", text)

    symbol = _parse_symbol(parsed.get("symbol"), allowed)
    if symbol is None:
        permitted = ", ".join(str(item) for item in allowed)
        return DecisionError(
            f"symbol {parsed.get('symbol')!r} is not one of the permitted symbols ({permitted})",
            text,
        )

    confidence = _parse_confidence(parsed.get("confidence"))
    if confidence is None:
        return DecisionError(f"invalid confidence {parsed.get('confidence')!r}", text)

    reason = parsed.get("reason")
    if not isinstance(reason, str) or not reason.strip():
        # An unexplained decision cannot be reviewed after a loss, which makes it
        # worthless as a record even when it happens to be right.
        return DecisionError("reason is missing or empty", text)

    return AIDecision(
        action=action,
        symbol=symbol,
        confidence=confidence,
        reason=reason.strip()[:1000],
        raw=text,
    )


def _extract_json(text: str) -> str | None:
    """Pull the JSON object out of a response, or ``None`` if it is ambiguous."""
    stripped = text.strip()
    if stripped.startswith("{") and stripped.endswith("}"):
        return stripped

    fenced: list[str] = _FENCE.findall(text)
    if len(fenced) == 1:
        return fenced[0]
    if len(fenced) > 1:
        # Two candidate answers is not a formatting quirk; picking one would be a guess.
        return None

    # A single bare object surrounded by prose is still unambiguous.
    first, last = text.find("{"), text.rfind("}")
    if first != -1 and last > first:
        candidate = text[first : last + 1]
        if candidate.count("{") == candidate.count("}"):
            return candidate
    return None


def _parse_action(value: object) -> Action | None:
    """Strict action parsing. Case-insensitive, nothing else."""
    if not isinstance(value, str):
        return None
    try:
        return Action(value.strip().upper())
    except ValueError:
        return None


def _parse_symbol(value: object, allowed: tuple[Symbol, ...]) -> Symbol | None:
    """Resolve a symbol against the permitted set.

    Accepts both ``BTCUSDT`` and ``BTC/USDT`` because models produce either, and the
    difference is notation rather than meaning. Anything not in ``allowed`` is refused.
    """
    if not isinstance(value, str) or not value.strip():
        return None
    wanted = value.strip().upper().replace("-", "").replace("/", "")
    for symbol in allowed:
        if f"{symbol.base}{symbol.quote}".upper() == wanted:
            return symbol
    return None


def _parse_confidence(value: object) -> Decimal | None:
    """Confidence as a Decimal in [0,1], or ``None``.

    Booleans are refused explicitly: ``True`` is an ``int`` in Python and would otherwise
    slip through as a confidence of 1.0, which is the most dangerous value in the range.
    """
    if isinstance(value, bool):
        return None
    if not isinstance(value, (int, float, str)):
        return None
    try:
        parsed = Decimal(str(value))
    except (InvalidOperation, ValueError):
        return None
    if not parsed.is_finite() or parsed < ZERO or parsed > Decimal("1"):
        return None
    return parsed


__all__ = ["AIDecision", "Action", "DecisionError", "parse_decision"]
