"""Declarative base and shared column types.

A naming convention is set on the metadata so Alembic emits stable, predictable constraint
names — without it, autogenerated migrations produce unnamed constraints that cannot be
dropped on downgrade.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Annotated, Any

from sqlalchemy import DateTime, MetaData, Numeric, String, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

#: 28 digits of precision covers BTC quantities at 8dp and USD notionals into the
#: trillions without ever silently truncating. Prices and quantities are stored as
#: NUMERIC, never DOUBLE PRECISION: a float column would reintroduce exactly the
#: rounding error the Decimal domain layer exists to prevent.
PRICE_PRECISION = 28
PRICE_SCALE = 12

Amount = Annotated[Decimal, mapped_column(Numeric(PRICE_PRECISION, PRICE_SCALE))]
UtcTimestamp = Annotated[datetime, mapped_column(DateTime(timezone=True))]
Uuid = Annotated[str, mapped_column(String(36))]
ShortText = Annotated[str, mapped_column(String(64))]
MediumText = Annotated[str, mapped_column(String(255))]


class Base(DeclarativeBase):
    """Declarative base for every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {  # noqa: RUF012 — SQLAlchemy reads this as a class attribute
        Decimal: Numeric(PRICE_PRECISION, PRICE_SCALE),
        datetime: DateTime(timezone=True),
    }

    def to_dict(self) -> dict[str, Any]:
        """Shallow column dict, useful for logging and debugging."""
        return {column.name: getattr(self, column.name) for column in self.__table__.columns}

    def __repr__(self) -> str:
        identity = getattr(self, "id", None)
        return f"<{type(self).__name__} id={identity!r}>"


class TimestampMixin:
    """Server-side created/updated timestamps.

    Defaults are computed by Postgres (``now()``) rather than by Python so that rows
    written by migrations, psql or a second process all carry consistent times.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False, index=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class UuidPkMixin:
    """String UUID primary key generated in the application layer.

    Application-side generation lets us build a complete aggregate (order plus fills)
    in memory and insert it in one round trip, and it keeps ids stable across a
    rollback-and-retry.
    """

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
